# -*- coding: utf-8 -*-
"""InterviewPilot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B_X6-q2w9fsN_6T1m2pi16FIX_5OSjQV
"""

!pip install --upgrade google-generativeai

from google.colab import userdata
import google.generativeai as genai

api_key = userdata.get("OPENAI_KEY")

if not api_key:
    raise ValueError("❌ API key not found. Add 'GEMINI_KEY' in Colab → Secrets.")

genai.configure(api_key=api_key)

print("✅ API key loaded successfully!")

# ✅ AI Interviewer Agent using Gemini (chat mode)

def interview_agent(role):
    print(f"\n🎯 Starting interview for: {role}\n")

    system_prompt = f"""
    You are a professional interviewer for the role: {role}
    Rules:
      - Ask only ONE question at a time
      - After each answer, ask a follow-up
      - Focus on technical + scenario-based questions
    """

    # ✅ Using model available in your account
    model = genai.GenerativeModel("gemini-flash-latest")

    conversation = model.start_chat(history=[
        {"role": "user", "parts": [system_prompt]}
    ])

    # First question
    bot_reply = conversation.send_message("Start interview. Ask the first question.").text
    print("\n🤖 Interviewer:", bot_reply)

    while True:
        user_answer = input("\n🟡 Your answer (type 'exit' to stop): ")
        if user_answer.lower() == "exit":
            print("\n✅ Interview Finished! Good luck! 🚀")
            break

        bot_reply = conversation.send_message(user_answer).text
        print("\n🤖 Interviewer:", bot_reply)


# Run the interviewer
role = input("Enter job role (e.g., Data Analyst, ML Engineer): ")
interview_agent(role)

